version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - MOMENTO_API_KEY=${MOMENTO_API_KEY}
    depends_on:
      - phpredis

  phpredis:
    image: redis:latest
    ports:
      - "6379:6379"
