name: On Pull Request

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      php-version: 8.4
      extensions: grpc, protobuf

    steps:
      - uses: actions/checkout@v4

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v2
        with:
          project_status: official
          project_stability: beta
          project_type: other

      - name: Commit lint and Other Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set cache key
        id: cache-key
        run: echo "key=php-${{ env.php-version }}" >> $GITHUB_OUTPUT

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ steps.cache-key.outputs.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Check CS (Code Style)
        run: make lint-check

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set cache key
        id: cache-key
        run: echo "key=php-8.4-backend" >> $GITHUB_OUTPUT

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 8.4
          extensions: grpc, protobuf
          key: ${{ steps.cache-key.outputs.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: grpc, protobuf
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Run tests with Momento backend
        env:
          MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
          TEST_REDIS: false
        run: make test-momento

      - name: Run tests with Redis backend
        run: make test-redis
