name: On push to main

on:
  push:
    branches: [main]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: beta
          project_type: other
  lint:
    runs-on: ubuntu-latest
    env:
      php-version: 8.4
      extensions: grpc, protobuf

    steps:
      - uses: actions/checkout@v4

      - name: Set cache key
        id: cache-key
        run: echo "key=php-${{ env.php-version }}" >> $GITHUB_OUTPUT

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ steps.cache-key.outputs.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Check CS (Code Style)
        run: make lint-check

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set cache key
        id: cache-key
        run: echo "key=php-8.4-backend" >> $GITHUB_OUTPUT

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 8.4
          extensions: grpc, protobuf
          key: ${{ steps.cache-key.outputs.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: grpc, protobuf
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Run tests with Momento backend
        env:
          MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
          TEST_REDIS: false
        run: make test-momento

      - name: Run tests with Redis backend
        run: make test-redis

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: google-github-actions/release-please-action@v3
        name: Release Please
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          release-type: php
          package-name: momentohq/momento-php-redis-client
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Publish
        run: |
          echo "Published version: ${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release.outputs.release_created }}
